### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'depthwise'

### ISSUE THREAD

**Issue by JiamingLiu-Jeremy** [samb-t/infty-diff#2]
Hi, thank you for your great work. I have a question about ：
self.conv = spnn.Conv3d(embed_dim, embed_dim, kernel_size=(1,kernel_size,kernel_size), depthwise=depthwise, bias=False).

There is no "depthwise" in torchsparse:https://github.com/mit-han-lab/torchsparse, conv3d. Could you please clarify this ?

Thanks a lot !

**Comment by samb-t** [comment]
Hi, thanks for your interest! The official torchsparse repo doesn't support depthwise convolutions, I added it in my fork here: [https://github.com/samb-t/torchsparse](https://github.com/samb-t/torchsparse) which includes the setup instructions. Or if you directly setup the environment from [requirements.yml](https://github.com/samb-t/infty-diff/blob/main/requirements.yml) then it should hopefully compile this version. Hope this helps!
